project_name: go-puyo
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: main.go
    binary: go-puyo
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archives:
  name_template: >-
  {{ .ProjectName }}_
  {{ .Os }}_
  {{ .Arch }}
release:
  prerelease: auto
